# Generated by Django 5.2 on 2026-09-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CLIENT', 'Client')], default='CLIENT', max_length=10),
        ),
    ]
