# Generated by Django 5.2 on 2026-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('client', 'client')], default='client', max_length=10),
        ),
    ]
