# Generated by Django 5.2 on 2026-09-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('create_client', 'Can create client'), ('update_client', 'Can update client'), ('activate_client', 'Can activate or deactivate client'), ('create_admin', 'Can create admin'), ('update_admin', 'Can update admin'), ('activate_admin', 'Can activate or deactivate admin'), ('manage_permissions', 'Can manage user permissions')]},
        ),
    ]
