# Generated by Django 5.2 on 2026-09-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('create_client', 'Can create client'), ('update_client', 'Can update client'), ('activate_client', 'Can activate or deactivate client'), ('change_client_role', 'Can change client role'), ('create_admin', 'Can create admin'), ('update_admin', 'Can update admin'), ('activate_admin', 'Can activate or deactivate admin'), ('change_admin_role', 'Can change admin role'), ('manage_permissions', 'Can manage user permissions')]},
        ),
    ]
