# Generated by Django 5.2 on 2026-09-06 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apikey',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='contractsapp.contract'),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contracthistory',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='contractsapp.contract'),
        ),
        migrations.AddConstraint(
            model_name='apikey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('contract',), name='unique_active_api_key_per_contract'),
        ),
    ]
