# Generated by Django 5.2 on 2026-09-08 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='APIKey',
            new_name='APIKeyModel',
        ),
        migrations.RenameModel(
            old_name='ContractHistory',
            new_name='ContractHistoryModel',
        ),
        migrations.RenameModel(
            old_name='Contract',
            new_name='ContractModel',
        ),
        migrations.RenameModel(
            old_name='Parameter',
            new_name='ParameterModel',
        ),
    ]
