# Generated by Django 5.2 on 2026-09-08 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0003_rename_apikey_apikeymodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contractmodel',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='contract_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='contractmodel',
            constraint=models.CheckConstraint(condition=models.Q(('rate_limit__gt', 0)), name='contract_rate_limit_gt_zero'),
        ),
        migrations.AddField(
            model_name='contractparametermodel',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_parameter_assignments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractparametermodel',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contractsapp.contractmodel'),
        ),
        migrations.AddField(
            model_name='contractparametermodel',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parameters', to='contractsapp.parametermodel'),
        ),
        migrations.AddConstraint(
            model_name='contractparametermodel',
            constraint=models.UniqueConstraint(fields=('contract', 'parameter'), name='unique_contract_parameter'),
        ),
    ]
