# Generated by Django 5.2 on 2026-09-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0004_contractparametermodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='used_requests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractparametermodel',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_parameters', to='contractsapp.contractmodel'),
        ),
        migrations.AlterField(
            model_name='contractparametermodel',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_parameters', to='contractsapp.parametermodel'),
        ),
        migrations.AddConstraint(
            model_name='contractmodel',
            constraint=models.CheckConstraint(condition=models.Q(('request_quota__gt', 0)), name='contract_request_quota_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='contractmodel',
            constraint=models.CheckConstraint(condition=models.Q(('request_quota__gte', models.F('used_requests'))), name='contract_quota_gte_used_requests'),
        ),
    ]
