# Generated by Django 5.2 on 2026-09-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0005_contractmodel_used_requests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikeymodel',
            options={'permissions': [('manage_api_key', 'Can manage API keys')]},
        ),
        migrations.AlterModelOptions(
            name='contractmodel',
            options={'permissions': [('renew_contract', 'Can renew contract'), ('view_contract_history', 'Can view contract history')]},
        ),
        migrations.AlterModelOptions(
            name='contractparametermodel',
            options={'permissions': [('assign_parameter', 'Can assign parameter to contract'), ('remove_parameter', 'Can remove parameter from contract')]},
        ),
    ]
