# Generated by Django 5.2 on 2026-07-26 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadfilemodel',
            old_name='user',
            new_name='uploaded_by',
        ),
        migrations.RenameField(
            model_name='userpointmodel',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
