# Generated by Django 5.2 on 2026-09-08 09:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationsapp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='PointModel',
        ),
        migrations.RenameModel(
            old_name='UserPoint',
            new_name='UserPointModel',
        ),
    ]
