# Generated by Django 5.2 on 2026-09-09 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractsapp', '0005_contractmodel_used_requests_and_more'),
        ('locationsapp', '0004_alter_userpointmodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_point_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_points', to='contractsapp.contractmodel')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_points', to='locationsapp.pointmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='UserPointModel',
        ),
        migrations.AddConstraint(
            model_name='contractpointmodel',
            constraint=models.UniqueConstraint(fields=('contract', 'point'), name='unique_contract_point'),
        ),
    ]
