# Generated by Django 5.2 on 2026-09-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationsapp', '0005_contractpointmodel_delete_userpointmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractpointmodel',
            options={'permissions': [('assign_point', 'Can assign point to contract'), ('remove_point', 'Can remove point from contract')]},
        ),
    ]
